menu:
  Home: /
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: G-1Q54XSFMZL
rss:

comment_provider: gitalk
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
# Disqus comments
disqus:
  shortname: caoyusheng
# Gitalk
gitalk:
  owner: vforkliu
  repo: tatamobile_commnets
  oauth:
    accessToken:
    clientId: 123456789012345
    clientSecret: 123456789012345
  admin:
    - vforkliu
  distractionFreeMode: false
